import formatDate from "./dateFormatter";


export default function prepareGetOne(result) {
  return {
    auditName: result.auditName,
    overallTechHealth: result.overallTechHealth,
    overallInformation: result.overallInformation,
    computerCovered: result.computerCovered,
    hostingCost: result.hostingCost,
    contractCost: result.contractCost,
    overallBackupLevel: result.overallBackupLevel,
    overallSecurityLevel: result.overallSecurityLevel,
    overallHardwareLevel: result.overallHardwareLevel,
    onlinePremiseServersStatus: result.onlinePremiseServersStatus,
    onlineFileStorageStatus: result.onlineFileStorageStatus,
    onlineDedicatedServersStatus: result.onlineDedicatedServersStatus,
    emailOnlinePersonalStatus: result.emailOnlinePersonalStatus,
    personalComputerStatus: result.personalComputerStatus,
    fileTestRecovery: formatDate(result.fileTestRecovery),
    backupSuccessRate: result.backupSuccessRate,
    drStatus: result.drStatus,
    hardwareSystemSupport: result.hardwareSystemSupport,
    hardwareSystemOverdue: result.hardwareSystemOverdue,
    digitalMaturitIndex: result.digitalMaturitIndex,
    hardwareAssetsSupported: result.hardwareAssetsSupported,
    hardwareAssetsUnsupportedSoon: result.hardwareAssetsUnsupportedSoon,
    hardwareAssetsUnsupported: result.hardwareAssetsUnsupported,
    hardwareAssetsUnknown: result.hardwareAssetsUnknown,
    officeSuiteSupported: result.officeSuiteSupported,
    officeSuiteUnsupportedSoon: result.officeSuiteUnsupportedSoon,
    officeSuiteUnsupported: result.officeSuiteUnsupported,
    officeSuiteAssetsUnknown: result.officeSuiteAssetsUnknown,
    multiFactorAuthentication: result.multiFactorAuthentication,
    securityTrainingGiven: result.securityTrainingGiven,
    accountsAudited: result.accountsAudited,
    vulnerabilityManagement: result.vulnerabilityManagement,
    mobileDeviceManagement: result.mobileDeviceManagement,
    allComputersUpToDate: result.allComputersUpToDate,
    allComputersRunningAntiVirus: result.allComputersRunningAntiVirus,
    advanceEmailProtectionWithAdvancedMalware:
      result.advanceEmailProtectionWithAdvancedMalware,
    businessFilesProtected: result.businessFilesProtected,
    aiImplemented: result.aiImplemented,
    globalAdminsNames: result.globalAdminsNames,
    globalAdminsNamesStatus: result.globalAdminsNamesStatus,
    desktopAdminNames: result.desktopAdminNames,
    desktopAdminNamesStatus: result.desktopAdminNamesStatus,
    serverAdminNames: result.serverAdminNames,
    serverAdminNamesStatus: result.serverAdminNamesStatus,
    lucidicaSecurityPro: formatDate(result.lucidicaSecurityPro),
    microsoftSecureScore: result.microsoftSecureScore,
  };
}
