version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: audit-mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: audit
      MONGO_INITDB_ROOT_PASSWORD: audit

volumes:
  mongodb-data:
